### ISSUE TITLE
Clarification needed: Units for `pollingInterval` and `eventsFlushInterval`

### ISSUE THREAD

**Issue by kubosho** [bucketeer-io/bucketeer-docs#70]
When setting `pollingInterval` and `eventsFlushInterval` to arbitrary numbers, it was unclear from the documentation whether the values should be specified in seconds or milliseconds. Therefore, it seems more user-friendly to clearly specify the units.

> CUSTOM CONFIGURATION
> Depending on your use, you may want to change the optional configurations available.
>
> * pollingInterval (Minimum 5 minutes. Default is 10 minutes)
> * eventsFlushInterval (Default is 30 seconds)
> * eventsMaxQueueSize (Default is 50 events)
> * storageKeyPrefix (Default is empty)
> * userAgent (Default is window.navigator.userAgent)
> * fetch (Default is window.fetch)
>
> from: https://docs.bucketeer.io/sdk/client-side/javascript/#configuring-client

**Comment by kubosho** [comment]
From seeing the code, I understood that the values are to be specified in milliseconds:

https://github.com/bucketeer-io/javascript-client-sdk/blob/d24bed2a987f3a44a5914ccc7d3139a2a91349c6/src/BKTConfig.ts#L6-L10

**Comment by cre8ivejp** [comment]
> Seeing the code, I learned that values are specified in milliseconds:
> 
> https://github.com/bucketeer-io/javascript-client-sdk/blob/d24bed2a987f3a44a5914ccc7d3139a2a91349c6/src/BKTConfig.ts#L6-L10

@kubosho, thank you for reporting.
I'll add that information to the documentation.

**Comment by cre8ivejp** [comment]
@kubosho, I have updated the documentation!
https://docs.bucketeer.io/sdk/client-side/javascript
Thank you!

Commit: [189eb947](https://github.com/bucketeer-io/bucketeer-docs/commit/189eb947b08d432c9e5f3ede81bc085f93769c73)
